language: node_js
sudo: true
node_js:
- lts/*
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 47.103.209.220
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_94ff7340745c_key -iv $encrypted_94ff7340745c_iv
  -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
script:
- npm run build
- pwd
- ls
- cd ./html
- git init
- git add -A
- git commit -m 'deploy'
- git config --local user.name "zhairuihao"
- git config --local user.email "ruihao.zhai@gmail.com"
- git push -f https://${GITHUB_TOKEN}@github.com/zhairuihao/zhairuihao.github.io.git
  master
after_success:
- scp -r /home/travis/build/zhairuihao/vuepress-reco/html root@47.103.209.220:/root/data/docker/nginx/html
env:
  global:
    secure: EN2ha3ME0d7rwACposd2uuN9lvOEgqfFC+IBJRzjDdK3UEXRd/9Qs59VsxE6K4wk6iBX/zbBkSA3+VjuoZcEPDykjNeVMBSwnHNDMOcUQkDsQeYAR43eD7+TXWxTzQZtM7Q8ULup0AVGobFfHXJxTFzFGec4smFmLKKGeqPNHjJ3GHQD6bs0BfhLg8nw8Y8DTvs2S1DKK7ye3kyUkPyjmPQYBuEBN3BI1OVWpuQvdzrM5MZdvnaNkhhjc04wxJ4xDp4gqqTllM1tEMw5/5GkpsNyrP6/SyBSk/Kc1JB0fzOFBM8yhbt5ZNNi/dEMfjI9EkHOK7BPC+2rn6gw+QmeqsITrL/6bl6IgZu8TT9Gj4YriwY3klh2a99NtiTpUrM4AyD0wDkOBTr2myVwmcgQ4irIL0dZowjgu2WTc9oXuyJwxWWN48TVllurM8ONjpbXcj7mib9rL3hC3Md8nqIefExWSp3SWwz53WC6ZpPhTxJpSIDO1PkuzWATlggc9+/9SZWW8FoeDL8YOBAQqiVfi0G9TBkbg35aReu5lKNnEFeEeWEAb6W9Yb/KvmwIOfL82XpzRh1yqnIdUV1ah3yoJVSFSh700Tez3DT4YvJJIZ8RFox+5Rtnw+vXrhekdz893pnB6EiBgoqhOpv7yR3B1ihLdMbH7rYymC0FggEdoFw=
