language: node_js
node_js:
  - lts/*
branches:
  only:
    - master    # 构建的分支
cache:
  directories:
    - node_modules # 依赖缓存的目录
script:
  - npm run build
  - pwd
  - ls
  - cd ./html
    # 如果是发布到自定义域名
  # echo 'www.example.com' > CNAME
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git config --local user.name "zhairuihao"
  - git config --local user.email "ruihao.zhai@gmail.com"
    # 如果发布到 https://<USERNAME>.github.io
    # git push -f git@github.com:<USERNAME>/<USERNAME>.github.io.git master
    # 如果发布到 https://<USERNAME>.github.io/<REPO>
    # git push -f git@github.com:<USERNAME>/<REPO>.git master:gh-pages
    # 如果使用 travis 持续集成
    git push -f https://${GITHUB_TOKEN}@github.com/zhairuihao/<REPO>.git master
#deploy:
#  provider: pages
#  skip-cleanup: true
#  local_dir: ./html/ # 项目打包后生成的文件的目录
#  github-token: $GITHUB_TOKEN # 这里这个变量就是刚才配置 token 时填写的那个变量
#  keep-history: true
#  on:
#    branch: master # 项目源码所在的分支